name: Summary
on:
  # Schedule updates (every week)
  schedule: [{cron: "0 0 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main", "development"]}
jobs:
  github-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: McCzarny/ghsummary@development
        with:
          username: '" || echo "Test"; echo "'
          api_key: ${{ secrets.GEMINI_API_KEY }}
          output_path: github-summary.svg

